// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnxjbisrnvkgbogsyncy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJueGpiaXNybnZrZ2JvZ3N5bmN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Nzc2ODQsImV4cCI6MjA3MzQ1MzY4NH0.gQtmsqeWgtm3GdxudRCMwRupy1OxYqEKbBMy99xVerM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});